In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# Make sure that you have all these libaries available to run the code successfully
#from pandas_datareader import data
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import urllib.request, json
import os
import numpy as np
import tensorflow as tf # This code has been tested with TensorFlow 1.6
from sklearn.preprocessing import MinMaxScaler

In [3]:
pwd!

'/Users/lan/Downloads/Github'

'/Users/lan/Downloads/Github'

In [4]:
df = pd.read_csv("Kaggle/jpx-tokyo-stock-exchange-prediction/train_files/stock_prices.csv")
#df= pd.read_csv("/kaggle/input/jpx-tokyo-stock-exchange-prediction/train_files/stock_prices.csv")

In [5]:
df.head()

RowId        Date  SecuritiesCode    Open    High     Low   Close  \
0  20170104_1301  2017-01-04            1301  2734.0  2755.0  2730.0  2742.0   
1  20170104_1332  2017-01-04            1332   568.0   576.0   563.0   571.0   
2  20170104_1333  2017-01-04            1333  3150.0  3210.0  3140.0  3210.0   
3  20170104_1376  2017-01-04            1376  1510.0  1550.0  1510.0  1550.0   
4  20170104_1377  2017-01-04            1377  3270.0  3350.0  3270.0  3330.0   

    Volume  AdjustmentFactor  ExpectedDividend  SupervisionFlag    Target  
0    31400               1.0               NaN            False  0.000730  
1  2798500               1.0               NaN            False  0.012324  
2   270800               1.0               NaN            False  0.006154  
3    11300               1.0               NaN            False  0.011053  
4   150800               1.0               NaN            False  0.003026

RowId        Date  SecuritiesCode    Open    High     Low   Close  \
0  20170104_1301  2017-01-04            1301  2734.0  2755.0  2730.0  2742.0   
1  20170104_1332  2017-01-04            1332   568.0   576.0   563.0   571.0   
2  20170104_1333  2017-01-04            1333  3150.0  3210.0  3140.0  3210.0   
3  20170104_1376  2017-01-04            1376  1510.0  1550.0  1510.0  1550.0   
4  20170104_1377  2017-01-04            1377  3270.0  3350.0  3270.0  3330.0   

    Volume  AdjustmentFactor  ExpectedDividend  SupervisionFlag    Target  
0    31400               1.0               NaN            False  0.000730  
1  2798500               1.0               NaN            False  0.012324  
2   270800               1.0               NaN            False  0.006154  
3    11300               1.0               NaN            False  0.011053  
4   150800               1.0               NaN            False  0.003026

In [6]:
df.shape

(2332531, 12)

(2332531, 12)

In [7]:
df[df.SecuritiesCode==1332]

RowId        Date  SecuritiesCode   Open   High    Low  \
1        20170104_1332  2017-01-04            1332  568.0  576.0  563.0   
1866     20170105_1332  2017-01-05            1332  572.0  573.0  565.0   
3731     20170106_1332  2017-01-06            1332  567.0  576.0  563.0   
5596     20170110_1332  2017-01-10            1332  573.0  576.0  561.0   
7461     20170111_1332  2017-01-11            1332  559.0  562.0  551.0   
...                ...         ...             ...    ...    ...    ...   
2322532  20211129_1332  2021-11-29            1332  579.0  579.0  567.0   
2324532  20211130_1332  2021-11-30            1332  580.0  590.0  573.0   
2326532  20211201_1332  2021-12-01            1332  568.0  578.0  568.0   
2328532  20211202_1332  2021-12-02            1332  566.0  577.0  565.0   
2330532  20211203_1332  2021-12-03            1332  579.0  585.0  570.0   

         Close   Volume  AdjustmentFactor  ExpectedDividend  SupervisionFlag  \
1        571.0  2798500               1.0               NaN            False   
1866     568.0  2162900               1.0               NaN            False   
3731     575.0  2125600               1.0               NaN            False   
5596     562.0  2744600               1.0               NaN            False   
7461     553.0  2231800               1.0               NaN            False   
...        ...      ...               ...               ...              ...   
2322532  567.0  1607200               1.0               NaN            False   
2324532  573.0  2732300               1.0               NaN            False   
2326532  574.0  1661300               1.0               NaN            False   
2328532  573.0  1525800               1.0               NaN            False   
2330532  585.0  1195500               1.0               NaN            False   

           Target  
1        0.012324  
1866    -0.022609  
3731    -0.016014  
5596    -0.016275  
7461     0.016544  
...           ...  
2322532  0.001745  
2324532 -0.001742  
2326532  0.020942  
2328532  0.006838  
2330532 -0.056027  

[1202 rows x 12 columns]

RowId        Date  SecuritiesCode   Open   High    Low  \
1        20170104_1332  2017-01-04            1332  568.0  576.0  563.0   
1866     20170105_1332  2017-01-05            1332  572.0  573.0  565.0   
3731     20170106_1332  2017-01-06            1332  567.0  576.0  563.0   
5596     20170110_1332  2017-01-10            1332  573.0  576.0  561.0   
7461     20170111_1332  2017-01-11            1332  559.0  562.0  551.0   
...                ...         ...             ...    ...    ...    ...   
2322532  20211129_1332  2021-11-29            1332  579.0  579.0  567.0   
2324532  20211130_1332  2021-11-30            1332  580.0  590.0  573.0   
2326532  20211201_1332  2021-12-01            1332  568.0  578.0  568.0   
2328532  20211202_1332  2021-12-02            1332  566.0  577.0  565.0   
2330532  20211203_1332  2021-12-03            1332  579.0  585.0  570.0   

         Close   Volume  AdjustmentFactor  ExpectedDividend  SupervisionFlag  \
1        571.0  2798500               1.0               NaN            False   
1866     568.0  2162900               1.0               NaN            False   
3731     575.0  2125600               1.0               NaN            False   
5596     562.0  2744600               1.0               NaN            False   
7461     553.0  2231800               1.0               NaN            False   
...        ...      ...               ...               ...              ...   
2322532  567.0  1607200               1.0               NaN            False   
2324532  573.0  2732300               1.0               NaN            False   
2326532  574.0  1661300               1.0               NaN            False   
2328532  573.0  1525800               1.0               NaN            False   
2330532  585.0  1195500               1.0               NaN            False   

           Target  
1        0.012324  
1866    -0.022609  
3731    -0.016014  
5596    -0.016275  
7461     0.016544  
...           ...  
2322532  0.001745  
2324532 -0.001742  
2326532  0.020942  
2328532  0.006838  
2330532 -0.056027  

[1202 rows x 12 columns]

In [8]:
(575.0- 568.0)/568.0

0.01232394366197183

0.01232394366197183

sklearn.preprocessing.MinMaxScaler.fit_transform(df[[column]]) to return the Pandas DataFrame df from the first step with the specified column min-max scaled.

In [9]:
min_max_scaler = MinMaxScaler(feature_range=(0,1))
df[["Target", "Close"]] = min_max_scaler.fit_transform(df[["Target", "Close"]])

In [10]:
temp = df.groupby("SecuritiesCode")["Target", "Close"].agg(list)

<ipython-input-10-22840941fca5>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  temp = df.groupby("SecuritiesCode")["Target", "Close"].agg(list)
<ipython-input-10-22840941fca5>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  temp = df.groupby("SecuritiesCode")["Target", "Close"].agg(list)


In [11]:
temp

Target  \
SecuritiesCode                                                      
1301            [0.34113872791527505, 0.3424279969221406, 0.34...   
1332            [0.34796624129861925, 0.32739407564988965, 0.3...   
1333            [0.344332611819195, 0.3344052394617789, 0.3316...   
1375            [0.34099737566011507, 0.3308933933933934, 0.34...   
1376            [0.3472179565036493, 0.34373831277106537, 0.34...   
...                                                           ...   
9990            [0.3276836966768633, 0.3297675834964035, 0.333...   
9991            [0.3407085529178553, 0.3506369307864325, 0.343...   
9993            [0.3495668027393752, 0.3558999633783285, 0.330...   
9994            [0.3400419886038002, 0.3357036557099144, 0.340...   
9997            [0.3451143601856936, 0.3377931589996983, 0.337...   

                                                            Close  
SecuritiesCode                                                     
1301            [0.02490505404615834, 0.024868536371603855, 0....  
1332            [0.005085086181711948, 0.0050576979257960855, ...  
1333            [0.02917762196903301, 0.029542798714577854, 0....  
1375            [0.01895267309377739, 0.01848707274320771, 0.0...  
1376            [0.014022787028921997, 0.013913234005258544, 0...  
...                                                           ...  
9990            [0.0110374671340929, 0.011430032135553606, 0.0...  
9991            [0.010179301782062517, 0.010161042944785275, 0...  
9993            [0.0160586473853345, 0.016259494595384165, 0.0...  
9994            [0.0158851884312007, 0.016003870873502773, 0.0...  
9997            [0.006974875839906514, 0.007193981887233421, 0...  

[2000 rows x 2 columns]

Target  \
SecuritiesCode                                                      
1301            [0.34113872791527505, 0.3424279969221406, 0.34...   
1332            [0.34796624129861925, 0.32739407564988965, 0.3...   
1333            [0.344332611819195, 0.3344052394617789, 0.3316...   
1375            [0.34099737566011507, 0.3308933933933934, 0.34...   
1376            [0.3472179565036493, 0.34373831277106537, 0.34...   
...                                                           ...   
9990            [0.3276836966768633, 0.3297675834964035, 0.333...   
9991            [0.3407085529178553, 0.3506369307864325, 0.343...   
9993            [0.3495668027393752, 0.3558999633783285, 0.330...   
9994            [0.3400419886038002, 0.3357036557099144, 0.340...   
9997            [0.3451143601856936, 0.3377931589996983, 0.337...   

                                                            Close  
SecuritiesCode                                                     
1301            [0.02490505404615834, 0.024868536371603855, 0....  
1332            [0.005085086181711948, 0.0050576979257960855, ...  
1333            [0.02917762196903301, 0.029542798714577854, 0....  
1375            [0.01895267309377739, 0.01848707274320771, 0.0...  
1376            [0.014022787028921997, 0.013913234005258544, 0...  
...                                                           ...  
9990            [0.0110374671340929, 0.011430032135553606, 0.0...  
9991            [0.010179301782062517, 0.010161042944785275, 0...  
9993            [0.0160586473853345, 0.016259494595384165, 0.0...  
9994            [0.0158851884312007, 0.016003870873502773, 0.0...  
9997            [0.006974875839906514, 0.007193981887233421, 0...  

[2000 rows x 2 columns]

In [12]:
length_result=[]
for i in temp.Target:
    #print(len(i))
    length_result.append(len(i))
print(max(length_result), min(length_result))


1202 232
1202 232


In [13]:
def split_sequence(sequence, seq_length):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + seq_length
        # check if we are beyond the sequence
        if end_ix > len(sequence) - 1:
        # end in last Target
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:(end_ix+2)]
        X.append(seq_x)
        y.append(seq_y)
    #X = pad_sequences(X, maxlen=seq_length)
    return np.array(X), np.array(y)

In [45]:
temp1 = temp.Close.apply(split_sequence, seq_length=100)
x_raw = temp1.apply(lambda x: x[0]).to_numpy()
y_raw = temp1.apply(lambda x: x[1]).to_numpy()
non_empty_idx = [len(i) > 0 for i in x_raw]

X = np.concatenate(x_raw[non_empty_idx])
y = y_raw[non_empty_idx]
X.shape, y.shape

<ipython-input-13-f864dc4da495>:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(X), np.array(y)
<ipython-input-13-f864dc4da495>:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(X), np.array(y)


((2132531, 100), (2000,))

((2132531, 100), (2000,))

In [43]:
temp1[1301][0]

array([[0.02490505, 0.02486854, 0.0248868 , ..., 0.0279908 , 0.02785386,
        0.02748868],
       [0.02486854, 0.0248868 , 0.02495983, ..., 0.02785386, 0.02748868,
        0.02776256],
       [0.0248868 , 0.02495983, 0.02493244, ..., 0.02748868, 0.02776256,
        0.02776256],
       ...,
       [0.02639315, 0.02638402, 0.02620143, ..., 0.0272148 , 0.0268131 ,
        0.0263475 ],
       [0.02638402, 0.02620143, 0.02614665, ..., 0.0268131 , 0.0263475 ,
        0.02644793],
       [0.02620143, 0.02614665, 0.02609188, ..., 0.0263475 , 0.02644793,
        0.02664877]])

array([[0.02490505, 0.02486854, 0.0248868 , ..., 0.0279908 , 0.02785386,
        0.02748868],
       [0.02486854, 0.0248868 , 0.02495983, ..., 0.02785386, 0.02748868,
        0.02776256],
       [0.0248868 , 0.02495983, 0.02493244, ..., 0.02748868, 0.02776256,
        0.02776256],
       ...,
       [0.02639315, 0.02638402, 0.02620143, ..., 0.0272148 , 0.0268131 ,
        0.0263475 ],
       [0.02638402, 0.02620143, 0.02614665, ..., 0.0268131 , 0.0263475 ,
        0.02644793],
       [0.02620143, 0.02614665, 0.02609188, ..., 0.0263475 , 0.02644793,
        0.02664877]])

In [44]:
temp1[1301][1]

array([list([0.02776256208004674, 0.02776256208004674]),
       list([0.02776256208004674, 0.027808209173239846]),
       list([0.027808209173239846, 0.027853856266432952]), ...,
       list([0.026447925796085302, 0.026648773006134968]),
       list([0.026648773006134968, 0.0270961145194274]),
       list([0.0270961145194274])], dtype=object)

array([list([0.02776256208004674, 0.02776256208004674]),
       list([0.02776256208004674, 0.027808209173239846]),
       list([0.027808209173239846, 0.027853856266432952]), ...,
       list([0.026447925796085302, 0.026648773006134968]),
       list([0.026648773006134968, 0.0270961145194274]),
       list([0.0270961145194274])], dtype=object)

In [46]:
temp1[1301][1].shape

(1102,)

(1102,)

In [27]:
type(temp1)

pandas.core.series.Series

pandas.core.series.Series

In [39]:
temp1.iloc[0:1]

SecuritiesCode
1301    ([[0.02490505404615834, 0.024868536371603855, ...
Name: Close, dtype: object

SecuritiesCode
1301    ([[0.02490505404615834, 0.024868536371603855, ...
Name: Close, dtype: object

In [15]:
X

array([[0.02490505, 0.02486854, 0.0248868 , ..., 0.0279908 , 0.02785386,
        0.02748868],
       [0.02486854, 0.0248868 , 0.02495983, ..., 0.02785386, 0.02748868,
        0.02776256],
       [0.0248868 , 0.02495983, 0.02493244, ..., 0.02748868, 0.02776256,
        0.02776256],
       ...,
       [0.00880989, 0.0087825 , 0.00851775, ..., 0.00615323, 0.00597064,
        0.00596151],
       [0.0087825 , 0.00851775, 0.00838081, ..., 0.00597064, 0.00596151,
        0.00612584],
       [0.00851775, 0.00838081, 0.00828038, ..., 0.00596151, 0.00612584,
        0.00611671]])

array([[0.02490505, 0.02486854, 0.0248868 , ..., 0.0279908 , 0.02785386,
        0.02748868],
       [0.02486854, 0.0248868 , 0.02495983, ..., 0.02785386, 0.02748868,
        0.02776256],
       [0.0248868 , 0.02495983, 0.02493244, ..., 0.02748868, 0.02776256,
        0.02776256],
       ...,
       [0.00880989, 0.0087825 , 0.00851775, ..., 0.00615323, 0.00597064,
        0.00596151],
       [0.0087825 , 0.00851775, 0.00838081, ..., 0.00597064, 0.00596151,
        0.00612584],
       [0.00851775, 0.00838081, 0.00828038, ..., 0.00596151, 0.00612584,
        0.00611671]])

In [16]:
y

array([list([0.02776256208004674, 0.02776256208004674]),
       list([0.02776256208004674, 0.027808209173239846]),
       list([0.027808209173239846, 0.027853856266432952]), ...,
       list([0.006125839906514753, 0.006116710487876131]),
       list([0.006116710487876131, 0.006226263511539584]),
       list([0.006226263511539584])], dtype=object)

array([list([0.02776256208004674, 0.02776256208004674]),
       list([0.02776256208004674, 0.027808209173239846]),
       list([0.027808209173239846, 0.027853856266432952]), ...,
       list([0.006125839906514753, 0.006116710487876131]),
       list([0.006116710487876131, 0.006226263511539584]),
       list([0.006226263511539584])], dtype=object)

In [17]:
X[0]

array([0.02490505, 0.02486854, 0.0248868 , 0.02495983, 0.02493244,
       0.02480463, 0.02472247, 0.02455814, 0.02439381, 0.02446684,
       0.02451249, 0.02485941, 0.02470421, 0.02476811, 0.02480463,
       0.02482289, 0.02476811, 0.02483202, 0.02472247, 0.02484115,
       0.02478637, 0.02470421, 0.02474985, 0.02480463, 0.02485941,
       0.02485941, 0.02493244, 0.02527023, 0.02544369, 0.02565367,
       0.0256628 , 0.02567193, 0.02590016, 0.02618317, 0.026594  ,
       0.02660313, 0.02675833, 0.02676746, 0.02699569, 0.02739739,
       0.02744303, 0.02762562, 0.02826468, 0.02831033, 0.02849292,
       0.0286755 , 0.02849292, 0.0287668 , 0.02908633, 0.02853856,
       0.02872115, 0.02904068, 0.02894939, 0.02862986, 0.02831033,
       0.02840162, 0.02835597, 0.02831033, 0.02735174, 0.02673094,
       0.02667616, 0.02735174, 0.02735174, 0.02730609, 0.02673094,
       0.0267492 , 0.02658487, 0.02644793, 0.02630186, 0.0261923 ,
       0.02598233, 0.02631098, 0.02616491, 0.02632011, 0.02608

array([0.02490505, 0.02486854, 0.0248868 , 0.02495983, 0.02493244,
       0.02480463, 0.02472247, 0.02455814, 0.02439381, 0.02446684,
       0.02451249, 0.02485941, 0.02470421, 0.02476811, 0.02480463,
       0.02482289, 0.02476811, 0.02483202, 0.02472247, 0.02484115,
       0.02478637, 0.02470421, 0.02474985, 0.02480463, 0.02485941,
       0.02485941, 0.02493244, 0.02527023, 0.02544369, 0.02565367,
       0.0256628 , 0.02567193, 0.02590016, 0.02618317, 0.026594  ,
       0.02660313, 0.02675833, 0.02676746, 0.02699569, 0.02739739,
       0.02744303, 0.02762562, 0.02826468, 0.02831033, 0.02849292,
       0.0286755 , 0.02849292, 0.0287668 , 0.02908633, 0.02853856,
       0.02872115, 0.02904068, 0.02894939, 0.02862986, 0.02831033,
       0.02840162, 0.02835597, 0.02831033, 0.02735174, 0.02673094,
       0.02667616, 0.02735174, 0.02735174, 0.02730609, 0.02673094,
       0.0267492 , 0.02658487, 0.02644793, 0.02630186, 0.0261923 ,
       0.02598233, 0.02631098, 0.02616491, 0.02632011, 0.02608

In [18]:
X[0].shape

(100,)

(100,)

In [19]:
X[1]

array([0.02486854, 0.0248868 , 0.02495983, 0.02493244, 0.02480463,
       0.02472247, 0.02455814, 0.02439381, 0.02446684, 0.02451249,
       0.02485941, 0.02470421, 0.02476811, 0.02480463, 0.02482289,
       0.02476811, 0.02483202, 0.02472247, 0.02484115, 0.02478637,
       0.02470421, 0.02474985, 0.02480463, 0.02485941, 0.02485941,
       0.02493244, 0.02527023, 0.02544369, 0.02565367, 0.0256628 ,
       0.02567193, 0.02590016, 0.02618317, 0.026594  , 0.02660313,
       0.02675833, 0.02676746, 0.02699569, 0.02739739, 0.02744303,
       0.02762562, 0.02826468, 0.02831033, 0.02849292, 0.0286755 ,
       0.02849292, 0.0287668 , 0.02908633, 0.02853856, 0.02872115,
       0.02904068, 0.02894939, 0.02862986, 0.02831033, 0.02840162,
       0.02835597, 0.02831033, 0.02735174, 0.02673094, 0.02667616,
       0.02735174, 0.02735174, 0.02730609, 0.02673094, 0.0267492 ,
       0.02658487, 0.02644793, 0.02630186, 0.0261923 , 0.02598233,
       0.02631098, 0.02616491, 0.02632011, 0.02608275, 0.02623

array([0.02486854, 0.0248868 , 0.02495983, 0.02493244, 0.02480463,
       0.02472247, 0.02455814, 0.02439381, 0.02446684, 0.02451249,
       0.02485941, 0.02470421, 0.02476811, 0.02480463, 0.02482289,
       0.02476811, 0.02483202, 0.02472247, 0.02484115, 0.02478637,
       0.02470421, 0.02474985, 0.02480463, 0.02485941, 0.02485941,
       0.02493244, 0.02527023, 0.02544369, 0.02565367, 0.0256628 ,
       0.02567193, 0.02590016, 0.02618317, 0.026594  , 0.02660313,
       0.02675833, 0.02676746, 0.02699569, 0.02739739, 0.02744303,
       0.02762562, 0.02826468, 0.02831033, 0.02849292, 0.0286755 ,
       0.02849292, 0.0287668 , 0.02908633, 0.02853856, 0.02872115,
       0.02904068, 0.02894939, 0.02862986, 0.02831033, 0.02840162,
       0.02835597, 0.02831033, 0.02735174, 0.02673094, 0.02667616,
       0.02735174, 0.02735174, 0.02730609, 0.02673094, 0.0267492 ,
       0.02658487, 0.02644793, 0.02630186, 0.0261923 , 0.02598233,
       0.02631098, 0.02616491, 0.02632011, 0.02608275, 0.02623

In [20]:
y[0]

[0.02776256208004674, 0.02776256208004674]

[0.02776256208004674, 0.02776256208004674]

In [21]:
#from sklearn.preprocessing import MinMaxScaler
#scaler=MinMaxScaler(feature_range=(0,1))
#X=scaler.fit_transform(np.array(X).reshape(-1,1))
#test_data=scaler.fit_transform(np.array(test_data).reshape(-1,1))

In [22]:
X =X.reshape(X.shape[0],X.shape[1] , 2)
#X_test = X_test.reshape(X_test.shape[0],X_test.shape[1] , 1)

ValueError: cannot reshape array of size 213253100 into shape (2132531,100,2)

ValueError: cannot reshape array of size 213253100 into shape (2132531,100,2)

In [ ]:
X.shape

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM, GRU, Dropout

We will be using a sequential model and adding the layers of the LSTM as said, in the above sentence. The first layer should be the time step in 1.

In [ ]:
model=Sequential()
model.add(GRU(16, input_shape=(100,1))) #,return_sequences=True,
#model.add(Activation('relu'))
model.add(Dropout(0.5))
#model.add(GRU(50,return_sequences=True))
#model.add(GRU(50))
model.add(Dense(1,  activation="relu",))
model.compile(loss='mean_squared_error',optimizer='adam')
model.summary()

In [ ]:
H=model.fit(X,y,validation_split=0.1, epochs=10, batch_size=128)
#, callbacks=[EarlyStopping(monitor='val_loss', patience=4)])

In [ ]:
y_hat=model.predict(X)
#test_predict=model.predict(X_test)
#train_predict=scaler.inverse_transform(train_predict)
#test_predict=scaler.inverse_transform(test_predict)

In [ ]:
import math
from sklearn.metrics import mean_squared_error
math.sqrt(mean_squared_error(y,y_hat))

In [ ]:
def plot_loss(history):
    plt.plot(history.history['loss'], label='loss')
    plt.plot(history.history['val_loss'], label='val_loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

In [ ]:
import matplotlib.pyplot as plt
plot_loss(H)